@startuml
left to right direction

actor Administrador
actor Usuari
actor Usuari_Registrat

rectangle "Sistema de Venda d'Entrades" {
   Usuari --> (cercar esdeveniments)
   Usuari --> (comprar entrades)

   Usuari_Registrat  --> Usuari
   Usuari_Registrat  --> (veure historial de compres)
   Usuari_Registrat  --> (cancel·lar entrades)
   Administrador --> (nous esdeveniments)
   Administrador --> (Gestionar vendes)
}
@enduml