@startuml
actor Usuari as Us
boundary "Interfície" as In
control "Controlador" as Cont
entity "Factura" as F
Us --> In: demanarFactura()
activate In
In --> Cont: demanarFactura(num)
activate Cont
alt existeixFactura
    Cont --> F: getFactura(num)
    activate F
    F --> Cont: factura
    deactivate F
    Cont --> In: mostrarFactura
else no existeixFactura
    Cont --> In: mostrarError(noExisteixFactura)


end
@enduml