@startuml
left to right direction

actor Client
actor Administrador


rectangle " Sistema de Reserva d'Hotels" {
   Client --> (Cercar hotel)
   Client --> (fer compra)
   (fer compra) <.. (Recordatori reserva)
   Client --> (cancel·lar reserva)

   Administrador --> (Gestionar les reserves)
   Administrador --> (afegir nous hotels)



}
@enduml
