@startuml
left to right direction

actor Profesor
actor Alumne


rectangle " Plataforma d'E-learning" {
   Profesor --> ( crear cursos)
   Profesor --> (gestionar continguts)

   Alumne --> (inscriure a un curs)
   (inscriure a un curs) ..> (Validar pagament): << Include >>




}
@enduml