@startuml
left to right direction

actor Clients
actor Cuiners
actor Repartidors

rectangle "Sistema de Venda d'Entrades" {
   Clients --> (comanda)
   (comanda) --> (Fer pagament)
   (Fer pagament) ..> ( seleccionar plats): << Include >>
   (Fer pagament) <.. (Afegir propina): << Extend >>
   Cuiners --> (veure comandes pendents)
   Repartidors  --> ( lliurar comandes)
   Repartidors  --> (notificar entrega)
}
@enduml