@startuml
left to right direction

actor Clients
actor Cuiners
actor Repartidors

rectangle "Sistema de Venda d'Entrades" {
   Clients --> (seleccionar plats)
   (seleccionar plats) --> (Fer pagament)
   (Fer pagament) ..> ( comanda): << Include >>
   (Fer pagament) ..> (Afegir propina): << Extend >>
   (Afegir propina) ..> ( comanda): << Include >>
   Cuiners --> (veure comandes pendents)
   ( comanda) --> (veure comandes pendents)
   Repartidors  --> ( lliurar comandes)
   Repartidors  --> (notificar entrega)
}
@enduml